export const sampleEntries = [
  {
    id: "1",
    mood: 7,
    stress: 5,
    sleepHours: 7.5,
    studyHours: 4,
    energyLevel: 7,
    motivationLevel: 7,
    journalEntry: "Feeling okay and ready to work.",
    examDate: "",
    createdAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "2",
    mood: 6,
    stress: 6,
    sleepHours: 6.5,
    studyHours: 5,
    energyLevel: 6,
    motivationLevel: 6,
    journalEntry: "A little tired after a long study session.",
    examDate: "",
    createdAt: "2026-06-02T09:00:00.000Z",
  },
  {
    id: "3",
    mood: 5,
    stress: 7,
    sleepHours: 5.5,
    studyHours: 6,
    energyLevel: 5,
    motivationLevel: 5,
    journalEntry: "Stress is higher today with a deadline approaching.",
    examDate: "",
    createdAt: "2026-06-03T09:00:00.000Z",
  },
  {
    id: "4",
    mood: 4,
    stress: 8,
    sleepHours: 5,
    studyHours: 7,
    energyLevel: 4,
    motivationLevel: 4,
    journalEntry: "Feeling exhausted and a bit overwhelmed.",
    examDate: "2026-06-10",
    createdAt: "2026-06-04T09:00:00.000Z",
  },
  {
    id: "5",
    mood: 3,
    stress: 9,
    sleepHours: 4.5,
    studyHours: 8,
    energyLevel: 3,
    motivationLevel: 3,
    journalEntry: "Burnout is creeping in and sleep is poor.",
    examDate: "2026-06-10",
    createdAt: "2026-06-05T09:00:00.000Z",
  },
];

export const sampleAnalyses = [
  {
    id: "analysis-1",
    checkInId: "5",
    emotion: "Tired",
    trigger: "Academic workload",
    sentiment: "Negative",
    risk: "Elevated",
    recommendations: ["Take one small recovery action before returning to study."],
    createdAt: "2026-06-05T09:05:00.000Z",
  },
];
